export type InputSize = 'l' | 'm' | 's' | 'xs'
export type InputType = 'filled-secondary' | 'floating'
export type InputStatus =
	| 'disabled'
	| 'active'
	| 'filled'
	| 'error'
	| 'default'
	| 'hover'
export type InputCustom = 'white' | ''
