export type InputSize = 'xxl' | 'xl' | 'l' | 'm' | 's'
export type InputType = 'filled-secondary' | 'floating' | 'separated' | 'outline'
export type InputStatus =
	| 'disabled'
	| 'active'
	| 'filled'
	| 'error'
	| 'default'
	| 'hover'
export type InputCustom = 'white' | ''
