export type ButtonSize = 'l' | 'm' | 's' | 'xs'
export type ButtonType =
	| 'filled-primary'
	| 'filled-accent'
	| 'filled-secondary'
	| 'floating'
	| 'outline-primary'
	| 'outline-accent'
	| 'ghost-primary'
	| 'ghost-secondary'
